Desktop version
Akhtar-Joomun/portfolio pull request #5
Opened 2021-06-17 01:50 UTC by Ak0706

Media queries used for a desktop version website.
Layout changes from mobile version to desktop version at the width of 992px

2021-06-17 02:24 UTC, vichuge requested changes
# Required Changes ♻️ ⚠️ 🚦 

Hi @Ak0706, 

Good job so far!
Excellente project!!! But we need to make some changes to improve it.

![mario_ladders](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

## Good points 👍 
- No Linters error ✔️ 
- Your mobile design is excellent ✔️ 

## Aspects to improve ♻️

- [ ] The mobile design is good, but according to this project, you need to have desktop size too. I recommend you to check the Figma template to know how should look on the desktop because, at this point, both are the same.
- This is the problem in tablet (with blank spaces on both sides), when you see it, is the same as mobile but, it should be different.
![image](https://user-images.githubusercontent.com/20563252/122320986-bfc49c80-cee8-11eb-9df9-68e370aeda9d.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-17 08:44 UTC, Ak0706 commented
Ok, thank you for the review, but I still have some questions.

I made the mistake of removing the width from the mobile version.
But for the desktop version, it was set to 100%. Isn't that better than setting it to 1440px?
Otherwise, it doesn't fit my screen. 

Please let me know what I should do.
Thanks again.

2021-06-17 21:46 UTC, Shaher-11 requested changes
#### Hello @Ak0706 

### Great work on making the changes requested by the previous reviewer:clap::clap::clap:
You've done a good job implementing some of the requested changes but there are still some which aren't done yet,  so we need to implement those changes to get the project approved:muscle::muscle::muscle:

 ## Required Changes ♻️

- [x] You need to make sure that your desktop version looks like the one in the Figma [design template](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471).
- [ ] Check the comments below:point_down:


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Happy Coding!👏👏👏

2021-06-17 21:46 UTC, Shaher-11 commented on index.html
> +            </div>
Kindly align the nav elements and the rest of the section as the given design

### Original design 
![right1](https://user-images.githubusercontent.com/58376020/122475205-9b3df280-cfc4-11eb-8971-dff2bd5cb346.png)

#### Your project
![wrong1](https://user-images.githubusercontent.com/58376020/122475241-a8f37800-cfc4-11eb-8469-66dd8d14f98c.png)

2021-06-17 21:46 UTC, Shaher-11 commented on index.html
>                      <li>Codepen</li>
### Original design
[Orignal design](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1?node-id=1%3A1471)
#### Your Project
![wrong2](https://user-images.githubusercontent.com/58376020/122475584-29b27400-cfc5-11eb-829f-e97c832d93f2.png)


![wrong5](https://user-images.githubusercontent.com/58376020/122475955-b52c0500-cfc5-11eb-99b7-22600d041802.png)


![wrong4](https://user-images.githubusercontent.com/58376020/122475976-bc531300-cfc5-11eb-8e61-c67a7e1f5d09.png)

![wrong3](https://user-images.githubusercontent.com/58376020/122476017-ce34b600-cfc5-11eb-910a-273fe880f533.png)

2021-06-18 16:55 UTC, vichuge approved these changes
# Approved project! ✅ 🥳 🎈 🎉🎉🎉🎉🎉🎉🎉🎉 

Hi @Ak0706, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-18 17:24 UTC, merged